import { useEffect, useMemo, useState } from 'react';
import { Activity, Archive, ArrowDownLeft, ArrowUpRight, BarChart3, Bell, ChevronRight, CircleDollarSign, Download, FileUp, Home, LayoutGrid, Menu, Plus, RefreshCcw, Search, Settings, Sparkles, Target, Trash2, TrendingDown, TrendingUp, Wallet, X } from 'lucide-react';

type Kind = 'expense' | 'income';
type Entry = { id: string; kind: Kind; title: string; category: string; amount: number; date: string; recurring?: boolean };
type Goal = { id: string; name: string; target: number; saved: number };
type Tab = 'home' | 'activity' | 'lens' | 'destinations' | 'archive' | 'journey' | 'vault' | 'settings';

const seed: Entry[] = [
  { id:'1', kind:'expense', title:'Lunch', category:'Food', amount:450, date:'2026-09-24' },
  { id:'2', kind:'expense', title:'Metro', category:'Transport', amount:80, date:'2026-09-24' },
  { id:'3', kind:'income', title:'Freelance', category:'Work', amount:5000, date:'2026-09-23' },
  { id:'4', kind:'expense', title:'Internet', category:'Bills', amount:1200, date:'2026-09-18', recurring:true },
  { id:'5', kind:'expense', title:'Groceries', category:'Food', amount:7400, date:'2026-09-12' },
  { id:'6', kind:'income', title:'Salary', category:'Work', amount:30000, date:'2026-09-01' },
];
const initialGoals = [{id:'laptop',name:'Laptop',target:150000,saved:67500},{id:'travel',name:'Tokyo',target:90000,saved:22500}];
const money = (n:number) => `Rs. ${Math.round(n).toLocaleString('en-IN')}`;
const today = new Date().toISOString().slice(0,10);

function App() {
  const [entries,setEntries] = useState<Entry[]>(() => JSON.parse(localStorage.getItem('aurelis.entries') || 'null') || seed);
  const [goals,setGoals] = useState<Goal[]>(() => JSON.parse(localStorage.getItem('aurelis.goals') || 'null') || initialGoals);
  const [tab,setTab] = useState<Tab>('home');
  const [showSplash,setShowSplash] = useState(true);
  const [sheet,setSheet] = useState<Kind|null>(null);
  const [editing,setEditing] = useState<Entry|null>(null);
  const [query,setQuery] = useState('');
  const [toast,setToast] = useState('');
  const [lastDeleted,setLastDeleted] = useState<Entry|null>(null);

  useEffect(()=>{ localStorage.setItem('aurelis.entries',JSON.stringify(entries)); },[entries]);
  useEffect(()=>{ localStorage.setItem('aurelis.goals',JSON.stringify(goals)); },[goals]);
  useEffect(()=>{ const t=setTimeout(()=>setShowSplash(false),1250); return ()=>clearTimeout(t); },[]);
  useEffect(()=>{ if(!toast) return; const t=setTimeout(()=>setToast(''),2800); return ()=>clearTimeout(t); },[toast]);

  const income = entries.filter(e=>e.kind==='income').reduce((a,e)=>a+e.amount,0);
  const spent = entries.filter(e=>e.kind==='expense').reduce((a,e)=>a+e.amount,0);
  const balance = 15000 + income - spent;
  const filtered = entries.filter(e => `${e.title} ${e.category}`.toLowerCase().includes(query.toLowerCase()));
  const categoryTotals = useMemo(()=>Object.entries(entries.filter(e=>e.kind==='expense').reduce<Record<string,number>>((a,e)=>(a[e.category]=(a[e.category]||0)+e.amount,a),{})).sort((a,b)=>b[1]-a[1]),[entries]);
  const maxCategory = categoryTotals[0]?.[1] || 1;

  const remove = (entry:Entry) => { setLastDeleted(entry); setEntries(x=>x.filter(e=>e.id!==entry.id)); setToast('Removed · Undo'); };
  const undo = () => { if(lastDeleted){setEntries(x=>[lastDeleted,...x]);setLastDeleted(null);setToast('Restored');} };
  const exportJSON = () => { const blob=new Blob([JSON.stringify({entries,goals},null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aurelis-data.json';a.click();setToast('Data exported'); };
  const reset = () => { if(confirm('Reset all AURELIS data?')) {setEntries([]);setGoals(initialGoals);setToast('Vault reset');} };

  if(showSplash) return <div className="splash"><div className="splash-mark">✦</div><span>OCTAVIAN</span><i></i><strong>AURELIS</strong></div>;
  return <div className="app">
    <aside><Logo/><nav>{navItems.map(n=><button className={tab===n.id?'active':''} onClick={()=>setTab(n.id)} key={n.id}><n.icon size={18}/><span>{n.label}</span></button>)}</nav><div className="side-foot"><Sparkles size={16}/> Offline mode</div></aside>
    <main><header><div className="mobile-logo"><Logo/></div><div className="header-actions"><button className="icon-button"><Bell size={18}/></button><div className="avatar">O</div></div></header>
      {tab==='home' && <HomeView balance={balance} income={income} spent={spent} categoryTotals={categoryTotals} maxCategory={maxCategory} setSheet={setSheet} setTab={setTab}/>} 
      {tab==='activity' && <ActivityView entries={filtered} query={query} setQuery={setQuery} remove={remove} setEditing={setEditing}/>} 
      {tab==='lens' && <Lens entries={entries} spent={spent} categoryTotals={categoryTotals} setTab={setTab}/>} 
      {tab==='destinations' && <Destinations goals={goals} setGoals={setGoals}/>} 
      {tab==='archive' && <ArchiveView entries={entries}/>} 
      {tab==='journey' && <Journey entries={entries} income={income} spent={spent}/>} 
      {tab==='vault' && <Vault entries={entries} exportJSON={exportJSON} reset={reset} setEntries={setEntries} setToast={setToast}/>} 
      {tab==='settings' && <SettingsView setTab={setTab} />} 
    </main>
    <button className="quick-add" onClick={()=>setSheet('expense')}><Plus size={27}/></button>
    <div className="bottom-nav">{navItems.slice(0,2).map(n=><button className={tab===n.id?'active':''} onClick={()=>setTab(n.id)} key={n.id}><n.icon size={19}/><small>{n.label}</small></button>)}<button className="bottom-plus" onClick={()=>setSheet('expense')}><Plus size={25}/></button>{navItems.slice(2,4).map(n=><button className={tab===n.id?'active':''} onClick={()=>setTab(n.id)} key={n.id}><n.icon size={19}/><small>{n.label}</small></button>)}</div>
    {sheet && <EntrySheet kind={sheet} initial={editing} close={()=>{setSheet(null);setEditing(null)}} save={(e)=>{setEntries(x=>editing?x.map(v=>v.id===e.id?e:v):[e,...x]);setSheet(null);setEditing(null);setToast(editing?'Updated':'Added to activity')}}/>}
    {toast && <button className="toast" onClick={lastDeleted?undo:()=>setToast('')}>{toast}</button>}
  </div>
}
const navItems=[{id:'home' as Tab,label:'Home',icon:Home},{id:'activity' as Tab,label:'Activity',icon:Activity},{id:'lens' as Tab,label:'Lens',icon:BarChart3},{id:'destinations' as Tab,label:'Destinations',icon:Target},{id:'archive' as Tab,label:'Archive',icon:Archive},{id:'journey' as Tab,label:'Journey',icon:TrendingUp},{id:'vault' as Tab,label:'Data Vault',icon:Wallet},{id:'settings' as Tab,label:'Settings',icon:Settings}];
function Logo(){return <div className="logo"><div className="logo-symbol">✦</div><div><b>AURELIS</b><small>BY OCTAVIAN</small></div></div>}
function HomeView(p:{balance:number;income:number;spent:number;categoryTotals:[string,number][];maxCategory:number;setSheet:(k:Kind)=>void;setTab:(t:Tab)=>void}){return <div className="page"><div className="eyebrow">WEDNESDAY · 24 SEP 2026</div><section className="hero"><div><div className="eyebrow">CURRENT BALANCE</div><h1>{money(p.balance)}</h1><div className="flow"><span><ArrowUpRight size={15}/> {money(p.income)} income</span><span><ArrowDownLeft size={15}/> {money(p.spent)} spent</span></div></div><div className="orb">✦</div></section><div className="quick-row"><button onClick={()=>p.setSheet('expense')}><span className="cyan"><ArrowDownLeft size={18}/></span><b>Expense</b><small>Record spending</small></button><button onClick={()=>p.setSheet('income')}><span className="violet"><ArrowUpRight size={18}/></span><b>Income</b><small>Add incoming</small></button></div><section className="panel curve-panel"><PanelTitle title="SPENDING" action="VIEW LENS" onClick={()=>p.setTab('lens')}/><div className="curve"><svg viewBox="0 0 600 170" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#45e6e0" stopOpacity=".22"/><stop offset="1" stopColor="#45e6e0" stopOpacity="0"/></linearGradient></defs><path d="M0 145 C70 130 80 110 145 124 S210 78 260 105 S330 58 385 87 S470 42 530 58 S570 30 600 35 V170 H0Z" fill="url(#area)"/><path d="M0 145 C70 130 80 110 145 124 S210 78 260 105 S330 58 385 87 S470 42 530 58 S570 30 600 35" fill="none" stroke="#45e6e0" strokeWidth="3"/></svg></div><div className="category-list">{p.categoryTotals.slice(0,3).map(([name,value],i)=><div className="category" key={name}><span className={'dot d'+i}></span><span>{name}</span><strong>{money(value)}</strong><em style={{width:`${value/p.maxCategory*100}%`}}></em></div>)}</div></section><section className="section-heading"><h2>Today</h2><button onClick={()=>p.setTab('activity')}>All activity <ChevronRight size={16}/></button></section><div className="mini-activity"><ActivityRows entries={seed.slice(0,3)}/></div></div>}
function PanelTitle({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="panel-title"><span>{title}</span>{action&&<button onClick={onClick}>{action}<ChevronRight size={14}/></button>}</div>}
function ActivityRows({entries,remove,setEditing}:{entries:Entry[];remove?:(e:Entry)=>void;setEditing?:(e:Entry)=>void}){return <div className="rows">{entries.map(e=><div className="row" key={e.id}><span className={'entry-icon '+(e.kind==='income'?'income':'expense')}>{e.kind==='income'?<ArrowUpRight size={17}/>:<CircleDollarSign size={17}/>}</span><div className="row-main"><b>{e.title}</b><small>{e.category} · {e.date===today?'Today':e.date}</small></div><strong className={e.kind==='income'?'positive':''}>{e.kind==='income'?'+':'−'}{money(e.amount)}</strong>{remove&&<button className="row-action" onClick={()=>setEditing?.(e)}><Menu size={16}/></button>}</div>)}</div>}
function ActivityView(p:{entries:Entry[];query:string;setQuery:(v:string)=>void;remove:(e:Entry)=>void;setEditing:(e:Entry)=>void}){return <div className="page"><PageHeading title="Activity" kicker="TIMELINE"/><div className="search"><Search size={17}/><input placeholder="Search activity" value={p.query} onChange={e=>p.setQuery(e.target.value)}/></div><div className="panel activity-panel"><ActivityRows entries={p.entries} remove={p.remove} setEditing={p.setEditing}/></div></div>}
function Lens({entries,spent,categoryTotals,setTab}:{entries:Entry[];spent:number;categoryTotals:[string,number][];setTab:(t:Tab)=>void}){return <div className="page"><PageHeading title="Lens" kicker="SHORT OBSERVATIONS"/><div className="insights">{categoryTotals.slice(0,3).map(([n,v],i)=><div className="insight" key={n}><span className="insight-icon">{i===0?<TrendingUp size={19}/>:<TrendingDown size={19}/>}</span><div><b>{n} {i===0?'↑ 18%':'↓ 7%'}</b><small>{money(v)} this cycle</small></div><ChevronRight size={17}/></div>)}<div className="insight"><span className="insight-icon"><RefreshCcw size={18}/></span><div><b>Internet repeats monthly</b><small>Next · Rs. 1,200</small></div></div></div><div className="panel budget"><PanelTitle title="BUDGET"/><div className="budget-big"><strong>{Math.min(99,Math.round(spent/10000*100))}%</strong><span>{money(spent)} / Rs. 10,000</span></div><div className="progress"><i style={{width:`${Math.min(100,spent/10000*100)}%`}}/></div></div><button className="outline-button" onClick={()=>setTab('journey')}>Open full journey <ChevronRight size={16}/></button></div>}
function Destinations({goals,setGoals}:{goals:Goal[];setGoals:React.Dispatch<React.SetStateAction<Goal[]>>}){return <div className="page"><PageHeading title="Destinations" kicker="WHAT YOU'RE MOVING TOWARD"/><div className="goal-grid">{goals.map(g=><div className="panel goal" key={g.id}><div className="ring" style={{'--p':`${g.saved/g.target*360}deg`} as React.CSSProperties}><span>{Math.round(g.saved/g.target*100)}%</span></div><div><b>{g.name}</b><small>{money(g.saved)} / {money(g.target)}</small></div><button onClick={()=>setGoals(x=>x.filter(v=>v.id!==g.id))}><Trash2 size={15}/></button></div>)}</div><button className="outline-button" onClick={()=>{const name=prompt('Destination name?');if(name)setGoals(x=>[...x,{id:Date.now().toString(),name,target:100000,saved:0}])}}><Plus size={16}/> New destination</button></div>}
function ArchiveView({entries}:{entries:Entry[]}){return <div className="page"><PageHeading title="Archive" kicker="RECEIPTS"/><div className="receipt-grid">{entries.filter(e=>e.kind==='expense').map(e=><div className="receipt" key={e.id}><div className="receipt-art">{e.category==='Food'?'◒':e.category==='Transport'?'⌁':'▦'}</div><strong>{money(e.amount)}</strong><small>{e.date}</small></div>)}</div></div>}
function Journey({entries,income,spent}:{entries:Entry[];income:number;spent:number}){return <div className="page"><PageHeading title="Journey" kicker="REPORTS · SEP 2026"/><div className="report-stats"><div><small>IN</small><b>{money(income)}</b></div><div><small>OUT</small><b>{money(spent)}</b></div><div><small>NET</small><b className="positive">{money(income-spent)}</b></div></div><div className="panel report-chart"><div className="periods"><b>D</b><b>W</b><b className="selected">M</b><b>Y</b></div><div className="bars">{[35,52,42,74,58,88,68,94,75,61,82,65].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="panel"><PanelTitle title="MOMENTS"/><ActivityRows entries={entries.slice(0,4)}/></div></div>}
function Vault({entries,exportJSON,reset,setEntries,setToast}:{entries:Entry[];exportJSON:()=>void;reset:()=>void;setEntries:React.Dispatch<React.SetStateAction<Entry[]>>;setToast:(s:string)=>void}){const importData=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(String(r.result));if(Array.isArray(data.entries)){setEntries(data.entries);setToast('Data imported')}}catch{setToast('Invalid file')}};r.readAsText(file)};return <div className="page"><PageHeading title="Data Vault" kicker="LOCAL · ENCRYPTED IN SPIRIT"/><div className="vault-count"><strong>{entries.length}</strong><span>records stored<br/><small>Only on this device</small></span></div><div className="vault-actions"><button onClick={exportJSON}><Download/> Export JSON</button><label><FileUp/> Import JSON<input type="file" accept=".json" onChange={importData}/></label><button onClick={()=>{setEntries(x=>x.filter(e=>new Date(e.date)>=new Date(Date.now()-90*86400000)));setToast('Old records cleaned')}}><RefreshCcw/> Clean old</button><button className="danger" onClick={reset}><Trash2/> Reset vault</button></div></div>}
function SettingsView({setTab}:{setTab:(t:Tab)=>void}){return <div className="page"><PageHeading title="Settings" kicker="AURELIS CONTROL"/><div className="settings">{[['Currency','Rs. · INR'],['Theme','Midnight / Neon'],['Notifications','On'],['Daily Summary','Off'],['Weekly Summary','On'],['Monthly Summary','On'],['Hide Balance','Off']].map(([a,b])=><button key={a}><span>{a}</span><small>{b}<ChevronRight size={15}/></small></button>)}<button onClick={()=>setTab('vault')}><span>Data Vault</span><small><Wallet size={15}/><ChevronRight size={15}/></small></button></div></div>}
function PageHeading({title,kicker}:{title:string;kicker:string}){return <div className="page-heading"><div className="eyebrow">{kicker}</div><h1>{title}</h1></div>}
function EntrySheet({kind,initial,close,save}:{kind:Kind;initial:Entry|null;close:()=>void;save:(e:Entry)=>void}){const [title,setTitle]=useState(initial?.title||'');const [amount,setAmount]=useState(initial?.amount?.toString()||'');const [category,setCategory]=useState(initial?.category||'Food');return <div className="backdrop" onClick={close}><div className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-head"><h2>{initial?'Edit':'New'} {kind}</h2><button onClick={close}><X/></button></div><div className="kind-switch"><button className={kind==='expense'?'selected':''}>Expense</button><button className={kind==='income'?'selected':''}>Income</button></div><label>Amount<input autoFocus type="number" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>What was it?<input placeholder="e.g. Dinner" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['Food','Transport','Bills','Work','Shopping','Other'].map(c=><option key={c}>{c}</option>)}</select></label><button className="save-button" onClick={()=>amount&&title&&save({id:initial?.id||Date.now().toString(),kind,title,category,amount:Number(amount),date:initial?.date||today})}>Save entry <ArrowUpRight size={17}/></button></div></div>}
export default App;
